FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*

COPY hxckr-core /usr/local/bin/hxckr-core
COPY diesel /usr/local/bin/diesel
COPY migrations /migrations
COPY entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh /usr/local/bin/diesel

ENTRYPOINT ["/entrypoint.sh"]
