name: Build and Publish

on:
  push:
    branches: ["main"]
  release:
    types: [created]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/hxckr-core

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Docker image with Nix
        run: |
          nix-build docker-image.nix
          docker load < result

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      - name: Tag and push Docker image
        run: |
          docker tag hxckr-core:latest ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker tag hxckr-core:latest ${{ env.IMAGE_NAME }}:${{ github.event_name == 'release' && 'latest' || 'dev' }}
          docker push ${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker push ${{ env.IMAGE_NAME }}:${{ github.event_name == 'release' && 'latest' || 'dev' }}

      - name: Run migrations (Production)
        if: github.event_name == 'release'
        env:
          DATABASE_URL: ${{ secrets.PRODUCTION_DATABASE_URL }}
        run: |
          docker run --rm \
            -e DATABASE_URL \
            ${{ env.IMAGE_NAME }}:latest \
            diesel migration run

      - name: Print image size
        run: |
          docker image ls ${{ env.IMAGE_NAME }}
